### PR TITLE
Provenance Viewer for Taverna

### PR DESCRIPTION
**Pull request by PCStefan**
This is my first pull request. 

For the next I am going to redo it, The new version will have implemented the taverna server and a ontology datastore which will speed up the entire process.

### CODE REVIEW

**Comment by stain** [comment]
Thanks! 

Where does the sankey.js come from, is it from https://github.com/kunalb/d3-plugins/blob/sankey/sankey/sankey.js ?

(In which case we need to honour https://github.com/kunalb/d3-plugins/blob/sankey/LICENSE )

Any reason why you did "Add files via upload" rather than push your commits from https://github.com/PCStefan/Provenance-Viewer-for-Taverna ? (Are they the same content?)

**Comment by stain** [comment]
To what extent does this use the [ruby-graphviz](https://github.com/glejeune/Ruby-Graphviz) library? 

It is [Licensed as GPL 2](https://github.com/glejeune/Ruby-Graphviz/blob/master/COPYING.rdoc) which would be incompatible with the Apache license.

Would any of these work instead:

- [graphviz](https://rubygems.org/gems/graphviz) - MIT license
- [GraphvizR](https://rubygems.org/gems/GraphvizR) - MIT license

?

**Comment by PCStefan** [comment]
Hi Stian,

I believe the Graphviz is not required anymore. I have tried initially to
use GraphViz rather than D3.

With regards to the source of the D3 graphs, I used the followind

## Sankey diagram -  http://bl.ocks.org/d3noob/5028304


   - The sankey.ds is originally from here - from what I remember I have
   deleted/commented 2 or 3 lines.
   - If you want the original one, access
   http://bl.ocks.org/d3noob/raw/5028304/ with Google Chrome and
      1. right click on an empty space
      2. Go to Source and under *top -> bl.ocks.org <http://bl.ocks.org> ->
      d3noob/raw/5028304*, you should see *sankey.js*

## Adjacency matrix ( Co-occurrence graph) -
https://bost.ocks.org/mike/miserables/


I have used "add files via upload" since it was my first pull request and I
wasn`t able to suggest
https://github.com/PCStefan/Provenance-Viewer-for-Taverna as pull request.
They are the same.

I have started to do it from scratch. For this version, I want to do it
with Taverna Server and a datastore in order to reduce the content that
must be uploaded.

**Comment by stain** [comment]
Ah great, so we can remove the graphviz dependency.

http://bl.ocks.org/d3noob/5028304#license

> This block appears to have no license. Please contact the author to request a license

But the Sankey thing worries me a bit.. what is the license? It's not explicit.. is it open source?

Would you be OK to contact the original author to clarify if it has an [Apache-compatible license](https://www.apache.org/legal/resolved#category-a)?  

I see there's also
https://leanpub.com/D3-Tips-and-Tricks/read#leanpub-auto-sankey-diagrams
but that does not define its license either..

**Comment by PCStefan** [comment]
I have emailed D3noob.
The only thing to do right now is to wait for his reply.

**Comment by PCStefan** [comment]
Hi Stian,

I have received a reply from D3noob!

---------- Forwarded message ----------
From: D3noob <noreply-comment@blogger.com>
Date: 9 June 2016 at 07:29
Subject: [D3.js Tips and Tricks] New comment on Sankey Diagrams: A
Description of the d3.js Code.
To: padurariu.claudiu.stefan@gmail.com


D3noob <https://www.blogger.com/profile/03091573479428198379> has left a
new comment on the post "Sankey Diagrams: A Description of the d3.js Code
<http://www.d3noob.org/2013/02/sankey-diagrams-description-of-d3js-code.html?ext-ref=comm-sub-email>
":

Thanks for the contact Stefan. I am happy for you to use the code /
implimentation in any way that you would wish. I'm glad it was useful.

Post
<http://www.d3noob.org/2013/02/sankey-diagrams-description-of-d3js-code.html?ext-ref=comm-sub-email#comment-form>
a
comment.

Unsubscribe
<https://www.blogger.com/comment-unsubscribe.g?blogID=279772059074318326&postID=5916691927847667209>
to
comments on this post.

Posted by D3noob to D3.js Tips and Tricks
<http://www.d3noob.org/?ext-ref=comm-sub-email> at 8 June 2016 at 23:29

**Comment by stain** [comment]
Thanks, @PCStefan. I think we'll accept your patch for now, but raise this with @d3noob and legal-discuss@apache.org as I am not sure "I am happy for you to use the code in any way that you would wish"  is an open source license. :-)

**Comment by d3noob** [comment]
Hi @stain and @PCStefan. Apologies for the confusion for this. I think it can be simplified by clarifying that what I think @PCStefan is looking for is the licence for the sankey.js code which as a plugin for d3.js and can be found [here ](https://github.com/d3/d3-plugins). My (extremely humble) work simply uses the sankey plugin. I am not its author. If there is still some confusion about the code that I wrote that uses the sankey plugin, I apply no licence to it whatsoever, so the only concern would be the incumbent licence for the plugin.

**Comment by stain** [comment]
Thanks for the clarifications, @d3noob! So do I understand it right that on http://bl.ocks.org/d3noob/5028304#license `sankey.js` is from d3-plugins, and `index.html` is your work? 

In @PCStefan's pull request here I think only the js file is involved.

So https://github.com/PCStefan/incubator-taverna-databundle-viewer/blob/master/app/assets/javascripts/sankey.js should in theory be equal to  https://github.com/d3/d3-plugins/blob/master/sankey/sankey.js 
 
..which is covered by this [BSD-3 license](https://github.com/d3/d3-plugins/blob/master/LICENSE) (compatible with Apache License) - but looking at the [sankey.js history](https://github.com/d3/d3-plugins/commits/master/sankey/sankey.js) the (c) should probably also include @mbostock @nmalkin @hongtaobai and @jasondavies.


BTW, @d3noob , for the future if you say "no license"  that means no-one is allowed to redistribute or repurpose, as regular copyright laws apply if you don't specify any license (a license grants additional rights). [CC0](https://creativecommons.org/choose/zero/) is probably closer to what you mean?

**Comment by stain** [comment]
@PCStefan is https://github.com/PCStefan/incubator-taverna-databundle-viewer/blob/master/app/assets/javascripts/vertical_sankey.js just your modification of sankey.js?

**Comment by d3noob** [comment]
Perfect! Thanks @stain You got it spot on. Only the index.html file is mine. Also many thanks for the licence clarification. You are correct the [CC0 ](https://creativecommons.org/choose/zero/)licence seems to fit well with my intentions. Cheers.

**Comment by stain** [comment]
I found that the content of @PCStefan's [sankey.js](https://github.com/PCStefan/incubator-taverna-databundle-viewer/blob/master/app/assets/javascripts/sankey.js) almost matched https://github.com/kunalb/d3-plugins/blob/sankey/sankey/sankey.js (particularly the - so I've added @kunalb to the (c).

Thanks all! Now we know why it's cool to add those license headers in advance..

I'm adding:

```javascript
// Copyright (c) 2012-2015, Michael Bostock,
// Nathan Malkin, Kunal Bhalla, Claudiu Stefan Padurariu
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 
// * Redistributions of source code must retain the above copyright notice, this
//   list of conditions and the following disclaimer.
// 
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// 
// * The name Michael Bostock may not be used to endorse or promote products
//   derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL MICHAEL BOSTOCK BE LIABLE FOR ANY DIRECT,
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
// EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

and to LICENSE:

```
---------------------------------------------------
app/assets/javascripts/sankey.js is licensed as BSD-3 clause
https://github.com/d3/d3-plugins/blob/master/LICENSE
---------------------------------------------------
```

**Pull request merged**
